env: "rware"
map: rware-1color-medium-6ag-hard-v1
time_limit: 500


#sizes = {
#    "tiny": (1, 3),
#    "small": (2, 3),
#    "medium": (2, 5),
#    "large": (3, 5)}
#
#difficulty = {"-easy": 2, "medium": 1, "-hard": 0.5}
#
#id=f"rware-{colors}color-{size}-{agents}ag{diff}-v1",